name: dchest.org
author: "Dmitry Chestnykh"
permalink: /:year/:month/:day/:name/
url: https://dchest.org
#search_index: /search/data/search-index.js

filters:
  .html: [htmlmin, scripts, styles]

properties:
  like_title: "dchest.org"
  twitter_name: dchest
  urls:
    twitter: https://twitter.com/dchest
