name: dchest.com
author: "Dmitry Chestnykh"
permalink: /:year/:month/:day/:name/
url: https://dchest.com

tagindex:
  permalink: /tag/:lctag/
  layout: tag

search:
  index: /search/data/search-index.json
  exclude:
      - /404.html
      - /search/

filters:
  .html: [htmlmin, scripts, styles]

properties:
  like_title: "dchest.com"
  twitter_name: dchest
  urls:
    twitter: https://x.com/dchest
    bluesky: https://bsky.app/profile/dchest.com
    mastodon: https://mastodon.social/@dchest
    pixelfed: https://pixelfed.social/dchest

#compress:
#  methods:
#    - gzip
#    - br
#  extensions:
#    - txt
#    - html
#    - js
#    - css
#    - xml
#    - json
#    - svg
